[package]
name = "bevy_prototype_scheduler"
version = "0.1.0"
authors = ["ratys"]
edition = "2018"

[dependencies]
bevy.git = "https://github.com/bevyengine/bevy.git"
async-channel.version = "1.4.2"
event-listener.version = "2.4.0"
parking_lot.version = "0.11.0"